# Clean Compiled JavaScript Files
# Removes all .js and .js.map files from src/ and test/ directories
# These files are generated by TypeScript compilation and should only exist in dist/

Write-Host "Cleaning compiled JavaScript files from src/ and test/..." -ForegroundColor Cyan

# Remove .js files
$jsFiles = Get-ChildItem -Path src, test -Recurse -Filter *.js -ErrorAction SilentlyContinue
$jsCount = $jsFiles.Count
$jsFiles | Remove-Item -Force

# Remove .js.map files
$mapFiles = Get-ChildItem -Path src, test -Recurse -Filter *.js.map -ErrorAction SilentlyContinue
$mapCount = $mapFiles.Count
$mapFiles | Remove-Item -Force

Write-Host "✓ Removed $jsCount .js files" -ForegroundColor Green
Write-Host "✓ Removed $mapCount .js.map files" -ForegroundColor Green
Write-Host "Done!" -ForegroundColor Green

npm test -- --grep "audio"